<!-- 数据表格 -->
<table id="dg_user" class="easyui-datagrid" style="width:100%;height:100%" data-options="toolbar:'#tb',singleSelect:true,fit:true,pagination:true,pageSize:20,pageList:[10,20,50],loadMsg:'数据正在努力加载，请稍后...'">
  <thead>
    <tr>
      <th data-options="field:'selector',checkbox:true"></th>
      <th data-options="field:'Product_id',align:'center'">产品编号</th>
      <th data-options="field:'Creproject_id',align:'center'">创意项目编号</th>
      <th data-options="field:'Company_id',align:'center'">企业编号</th>
      <th data-options="field:'Product_name',align:'center'">产品名</th>
      <th data-options="field:'Product_price',align:'center'">价格</th>
      <th data-options="field:'Product_classify',align:'center'">分类</th>
      <th data-options="field:'Product_label',align:'center'">标签</th>
      <th data-options="field:'Product_picture',align:'center'">产品图片</th>
    </tr>
  </thead>
</table>