
<%@page contentType="text/html;charset=utf-8"%>
<div class="container">
	<div class="footer2Left">
		<p
			style="color:#cccccc;font-size:28px;margin-top:2px;margin-bottom:-2px;">创意</p>
		<p style="color:#cccccc;font-size:13px;margin-top:-2px;">CRETIVE</p>
	</div>
	<div class="footer2right">
		<p>众智协作·创意平台 All rights reserved. Version v3.0
			&nbsp;&nbsp;|&nbsp;&nbsp;网络文化经营许可证：苏网文(2015)2048-047&nbsp;&nbsp;|&nbsp;&nbsp;增值电信许可证：苏B1.B2
			- 22</p>
		<p>众智创意为创作者和兴趣家提供所需的一切资源与服务，并提供原创项目孵化、投融资对接、推广报道、成品预售、兴趣协作、社区交流</p>
	</div>
</div>