<!-- 工具栏 -->
<div id="tb">
  <p style="font-weight: bold;">兴趣项目评论管理</p>
  <input id="key_Name" class="easyui-textbox" data-options="prompt:'请输入查询关键词'"/>
  <input id="key_date" class="easyui-datebox" />
  <a id="btn_Query" href="javascript:void(0)" class="easyui-linkbutton" data-options="iconCls:'icon-search'">查询</a>
  <a id="btn_Add" href="javascript:void(0)" class="easyui-linkbutton" data-options="iconCls:'icon-add'">添加</a>
  <a id="btn_Edit" href="javascript:void(0)" class="easyui-linkbutton" data-options="iconCls:'icon-edit'">修改</a>
  <a id="btn_Del" href="javascript:void(0)" class="easyui-linkbutton" data-options="iconCls:'icon-cancel'">删除</a>
</div>