<%@page contentType="text/html;charset=utf-8" %>
<div class="bj1" style="background-image:url(/SmartgenPlatform/homePage/imgage/1.jpg);">
        <p id="time" >12<span style="font-size:12px;">月</span></p>
       <span style="font-size:25px;font-family:楷体;">本月创意之星</span>
      <div id="UserheadPortrait" ><img id="User_headPortrait" src="/SmartgenPlatform/homePage/imgage/zz1.jpg" style="width:100%;height:100%;border-radius:50px;"/><p id="User_name" style="color:black;font-size:18px;">哈哈哈</p></div>
     </div>
     <div class="bj2" style="background-image:url(/SmartgenPlatform/homePage/imgage/7.jpg);">
        <p id="time" >12<span style="font-size:12px;">月</span></p>
        <span style="font-size:25px;font-family:楷体;">本月兴趣之星</span>
        <div id="UserheadPortrait" ><img id="User_headPortrait" src="/SmartgenPlatform/homePage/imgage/head3.jpg" style="width:100%;height:100%;border-radius:50px;"/><p id="User_name" style="color:black;font-size:18px;">啦啦啦</p></div>
     </div>