<%@page contentType="text/html;charset=utf-8" %>
<div class="product-ziti " style="margin-top:70px;"><p >兴趣项目</p></div>
       <div class="xd-btn" style="text-align:center;">
          <hr class="xd1"><a class="btn btn-info" href="/SmartgenPlatform/interestingProject/interestingProject.jsp" style="margin-top:-28px;font-size:16px;background:#3F81AC;"> 更多项目</a><hr class="xd2">
       </div> 
       <div style="margin-top:30px;">
       <div class="project1" ><a href="#"><img id="Inproject_picture1" src="/SmartgenPlatform/homePage/imgage/sy11.jpg" style="width:100%;height:100%"/></a><p class="Inproject_title" style="font-size:20px;font-family:微软雅黑;text-align:center;"><a href="#" style="text-decoration:none;">户外垂钓</a></p></div>
       <div class="project2"><a href="#"><img id="Inproject_picture2" src="/SmartgenPlatform/homePage/imgage/sy8.jpg" style="width:100%;height:100%"/></a><p class="Inproject_title" style="font-size:20px;font-family:微软雅黑;text-align:center;"><a href="#" style="text-decoration:none;">英语电影字幕翻译</a></p></div>
       <div class="project2" ><a href="#"><img id="Inproject_picture3" src="/SmartgenPlatform/homePage/imgage/sy12.jpg" style="width:100%;height:100%"/></a><p class="Inproject_title" style="font-size:20px;font-family:微软雅黑;text-align:center;"><a href="#" style="text-decoration:none;">爬山-走起</a></p></div>
       <div class="project2" ><a href="/SmartgenPlatform/inprojectIntroduction/inprojectIntroduction.jsp"><img id="Inproject_picture4" src="/SmartgenPlatform/homePage/imgage/sy7.jpg" style="width:100%;height:100%"/></a><p class="Inproject_title" style="font-size:20px;font-family:微软雅黑;text-align:center;"><a href="/SmartgenPlatform/inprojectIntroduction/inprojectIntroduction.jsp" style="text-decoration:none;">我们一起去旅行</a></p></div>
      </div>