 <%@page contentType="text/html;charset=utf-8" %>
 <div class="product-ziti " ><p >产品项目</p></div>
       <div class="xd-btn" style="text-align:center;">
          <hr class="xd1"><a class="btn btn-info" href="/SmartgenPlatform/product/product.jsp" style="margin-top:-28px;font-size:16px;background:#3F81AC;"> 更多项目</a><hr class="xd2">
       </div> 
       <div class="zs1" style="float:left;"><img id="hot" src="/SmartgenPlatform/homePage/imgage/p1.jpg" style="width:100%;height:100%"/></div>
       
       <div class="all-zs">
      
       <div class="zs3" ><a href="/SmartgenPlatform/productIntroduction/productIntroduction.jsp"><img  id="Product_picture" src="/SmartgenPlatform/homePage/imgage/p5.jpg" style="width:100%;height:65%"/></a>
           <a href="#" style="text-decoration:none;"><p id="Product_name">Q钟表</p></a>
           	<p>&yen<span id="Product_price"> 25</span></p>
       </div>
       <div class="zs4" ><a href="#"><img id="Product_picture" src="/SmartgenPlatform/homePage/imgage/p6.png" style="width:100%;height:65%"/></a>
           	<a href="#" style="text-decoration:none;"><p id="Product_name">小台灯</p></a>
           	<p>&yen <span id="Product_price"> 20</span></p>
       </div>
       <div class="zs5"  ><a href="#"><img id="Product_picture" src="/SmartgenPlatform/homePage/imgage/p8.jpg" style="width:100%;height:65%"/></a>
           	<a href="#" style="text-decoration:none;"><p id="Product_name"> 儿童小玩鸭</p></a>
           	<p>&yen <span id="Product_price"> 15</span></p>
       </div>
       <div class="zs6" ><a href="#"><img id="Product_picture" src="/SmartgenPlatform/homePage/imgage/p10.jpg" style="width:100%;height:65%"/></a>
           <a href="#" style="text-decoration:none;"><p id="Product_name">迷你小风扇</p></a>
           	<p>&yen <span id="Product_price"> 20</span></p>
       </div>
       </div>
       
       <div class="zs2" style="margin-left:100px;float:left;"><img id="hot" src="/SmartgenPlatform/homePage/imgage/p4.jpg" style="width:100%;height:100%"/></div>   