<%@page contentType="text/html;charset=utf-8" %>
<div class="product-ziti " ><p >创意项目</p></div>
       <div class="xd-btn" style="text-align:center;">
          <hr class="xd1"><a class="btn btn-info" href="/SmartgenPlatform/creativeProject/creativeProject.jsp" style="margin-top:-28px;font-size:16px;background:#3F81AC;"> 更多项目</a><hr class="xd2">
       </div> 
       <div style="margin-top:30px;">
       <div class="project1" "><a href="/SmartgenPlatform/creProUserGet?Creproject_id=2"><img id="Creproject_picture1" src="/SmartgenPlatform/homePage/imgage/project2.jpg" style="width:100%;height:100%"/></a><p class="Creproject_title" ><a href="/SmartgenPlatform/CreProUserGet?Creproject_id=2" style="text-decoration:none;">树叶回收垃圾桶</a></p></div>
       <div class="project2" ><a href="/SmartgenPlatform/creProUserGet?Creproject_id=1"><img id="Creproject_picture2" src="/SmartgenPlatform/homePage/imgage/sy6.png" style="width:100%;height:100%"/></a><p class="Creproject_title" ><a href="/SmartgenPlatform/CreProUserGet?Creproject_id=1" style="text-decoration:none;">多功能婴儿车</a></p></div>
       <div class="project2" ><a href="/SmartgenPlatform/creProUserGet?Creproject_id=3"><img id="Creproject_picture3" src="/SmartgenPlatform/homePage/imgage/project3.jpg" style="width:100%;height:100%"/></a><p class="Creproject_title" ><a href="/SmartgenPlatform/CreProUserGet?Creproject_id=3" style="text-decoration:none;">小型高脚杯</a></p></div>
       <div class="project2"><a href="/SmartgenPlatform/creProUserGet?Creproject_id=4"><img id="Creproject_picture4" src="/SmartgenPlatform/homePage/imgage/project4.jpg" style="width:100%;height:100%"/></a><p class="Creproject_title" ><a href="/SmartgenPlatform/CreProUserGet?Creproject_id=4" style="text-decoration:none;">办公轻松用品</a></p></div>
      </div>