<%@ page language="java" import="java.util.*" pageEncoding="utf-8"%>
<div class="container" >
	<div class="classified-section">
	    <table class="table-content">
	       <tr>
             <td class="all-show" style="font-size:28px;"><a href="/SmartgenPlatform/product/product.jsp" >产品</a></td>
	         <td><a href="/SmartgenPlatform/product/product.jsp">生活手工</a></td>
	         <td><a href="/SmartgenPlatform/product/product.jsp">家具家居</a></td>
	          <td><a href="/SmartgenPlatform/product/product.jsp">科技数码</a></td>
	           <td><a href="/SmartgenPlatform/product/product.jsp">艺术娱乐</a></td>
	            <td><a href="/SmartgenPlatform/product/product.jsp">医疗健康</a></td>
	             <td><a href="/SmartgenPlatform/product/product.jsp">户外运动</a></td>
	              <td><a href="/SmartgenPlatform/product/product.jsp">其他</a></td>
	       </tr>
	    </table>
	    </div>
	   <div style="margin-top:50px;">
	    <div class="show1">
	     <div class="img">
	         <img src="img/p10.jpg" id="Product_picture1" width="100%" height="100%"/>
	         <p id="Product_name1" class="product-name">迷你小风扇</p>
	         <p class="product-price">&yen;<span id="Product_price1" >20</span></p>
	     </div>
	    </div>
	    <div class="show2">
	      <div class="img">
	         <img src="img/p5.jpg" id="Product_picture2" width="100%" height="100%"/>
	         <p id="Product_name2" class="product-name">Q钟表</p>
	         <p class="product-price">&yen;<span id="Product_price2" >25</span></p>
	     </div>
	    </div>
	    <div class="show3">
	     <div class="img">
	         <img src="img/p8.jpg" id="Product_picture3" width="100%" height="100%"/>
	         <p id="Product_name3" class="product-name">儿童小玩鸭</p>
	         <p class="product-price">&yen;<span id="Product_price3" >15</span></p>
	     </div>
	    </div>
	  </div>
     
	    <div class="show1" style="margin-top:40px;">
	     <div class="img">
	         <img src="img/p6.png" id="Product_picture4" width="100%" height="100%"/>
	         <p id="Product_name4" class="product-name">小台灯</p>
	         <p class="product-price">&yen;<span id="Product_price4" >20</span></p>
	     </div>
	    </div>
	   
	   <div class="show2" style="margin-top:40px;">
	      <div class="img">
	         <img src="img/product2.jpg" id="Product_picture5" width="100%" height="100%"/>
	         <p id="Product_name5" class="product-name">陶瓷小花瓶</p>
	         <p class="product-price">&yen;<span id="Product_price6" >25</span></p>
	     </div>
	    </div>
         <div class="show3" style="margin-top:40px;margin-bottom:80px;">
	      <div class="img">
	         <img src="img/product3.jpg" id="Product_picture6" width="100%" height="100%"/>
	         <p id="Product_name6" class="product-name">厨房神器</p>
	         <p class="product-price">&yen;<span id="Product_price6" >15</span></p>
	     </div>
	    </div>
	    
	    <div class="php">下一页</div>
	    
 </div>
	