<%@page contentType="text/html;charset=utf-8"%>
<p
	style="color:#339999;font-size:35px;text-align:center;margin-top:20px;">一个与有趣的人做有趣的事的平台</p>
<hr
	style="width:100%;height:0px;border:none;border-top:3px solid #337ab7;margin-bottom:0px;display:inline-block;">
<div class="footer1">
	<div class="container">
		<div class="footer1Left">
			<div class="lefttop">
				<img src="img/logo.png" style="width:50px;height:50px;" /> <span
					class="logoContent">众智协作平台</span>
				<hr style="width:80%;align:left;margin-top:5px;margin-left:-15px;">
				<p class="footer1Content">版权合作&nbsp;&nbsp;|&nbsp;&nbsp;改编权合作&nbsp;&nbsp;|&nbsp;&nbsp;衍生品合作&nbsp;&nbsp;|&nbsp;&nbsp;媒体合作&nbsp;&nbsp;|&nbsp;&nbsp;赛事活动合作</p>
				<p class="footer1Content">QQ:1300741099</p>
				<p class="footer1Content">邮箱:1300741099@qq.com</p>
				<p class="footer1Content">联系电话:38-83-423</p>
				<p class="footer1Content">在线时间：全天24小时</p>
			</div>
		</div>
		<div class="footer1right">
			<div class="righttop">
				<span style="color:#009999;font-size:30px;text-decoration:none;">|</span>&nbsp;&nbsp;
				<a href="/SmartgenPlatform/homePage/homePage.jsp">首页</a>&nbsp;&nbsp; <span
					style="color:#009999;font-size:30px;">|</span>&nbsp;&nbsp; <a
					href="/SmartgenPlatform/interestingProject/interestingProject.jsp">兴趣协作</a>&nbsp;&nbsp; <span
					style="color:#009999;font-size:30px;">|</span>&nbsp;&nbsp; <a
					href="/SmartgenPlatform/creativeProject/creativeProject.jsp">创意孵化</a>&nbsp;&nbsp; <span
					style="color:#009999;font-size:30px;">|</span>&nbsp;&nbsp; <a
					href="#">产品系列</a>&nbsp;&nbsp; <span
					style="color:#009999;font-size:30px;">|</span>&nbsp;&nbsp; <a
					href="/SmartgenPlatform/creativeProjectPublic/creprojectPublic.jsp">我要发布</a>&nbsp;&nbsp;
				<p>扫一扫，关注我们</p>
				<img src="img/sys.gif" style="width:90px;height:90px;" />
			</div>

		</div>
	</div>
</div>
<div class="footer2">
	<div class="container">
		<div class="footer2Left">
			<p
				style="color:#cccccc;font-size:28px;margin-top:2px;margin-bottom:-2px;">创意</p>
			<p style="color:#cccccc;font-size:13px;margin-top:-2px;">CRETIVE</p>
		</div>
		<div class="footer2right">
			<p>众智协作·创意平台 All rights reserved. Version v3.0
				&nbsp;&nbsp;|&nbsp;&nbsp;网络文化经营许可证：苏网文(2015)2048-047&nbsp;&nbsp;|&nbsp;&nbsp;增值电信许可证：苏B1.B2
				- 22</p>
			<p>众智创意为创作者和兴趣家提供所需的一切资源与服务，并提供原创项目孵化、投融资对接、推广报道、成品预售、兴趣协作、社区交流</p>
		</div>
	</div>
</div>