<%@page contentType="text/html;charset=utf-8" %>
<div class="right-main">您还没有购买任何产品哦...</div>
				<div style="margin-left:280px;margin-top:150px;"><img src="img/person4.jpg" width="250px" height="250px"/>
				<span>你还没有购买，购买一个体验下吧</span>
				</div>
			   <div style="margin-left:350px;margin-top:250px;">
			   <button id="botton" type="button"
			class="btn btn-info glyphicon glyphicon-plus-sign btn-lg">去买买买！！！</button>
			   </div>