<%@page contentType="text/html;charset=utf-8"%>
  <div class="main">
       <div class="show-picture">
          <img src="img/p5.jpg" id="Product_picture" width="100%" height="100%"/>
       </div>
     
       <div class="product-name">
       <p style="font-size:14px;">众智平台 质量保证 放心购买</p>
       <p id="Product_name">Q钟表</p>
       </div>
       <div class="product-price">
         <p>&yen;<span id="Product_price">25</span></p>
       </div>
      <div class="right-show">
       <div class="glyphicon glyphicon-map-marker">江西 九江</div>&nbsp;&nbsp;
       <div class="glyphicon glyphicon-tint">已售66</div>
       <div class="show-fee">运费:&nbsp;&nbsp;0.00</div>
       <div class="show-fee">配送:&nbsp;&nbsp;<input type="text" value="输入详细地址"/> 48小时内发货</div>
      <div class="show-fee">数量:&nbsp;&nbsp;<input type="text" value="输入数量"/></div>
      </div>
      <div class="right-show">库存100件</div>
      <button id="botton1" type="button" class="btn btn-info ">预购</button>
		<button id="botton2" type="button" class="btn btn-info ">直接购买</button>	
   </div>
      